language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nghilt19411/travisci-testing -f Dockerfile.dev .

script: 
  - docker run -e CI=true nghilt19411/travisci-testing npm run test
